import { File } from '../types';

export const files: File[] = [
  {
    id: 1,
    name: 'Document1.pdf',
    dateModified: 'Nov 10, 2024',
    size: 245,
    type: 'pdf',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 2,
    name: 'Document2.docx',
    dateModified: 'Nov 8, 2024',
    size: 150,
    type: 'docx',
    isSelected: false,
    isFavorite: true,
  },
  {
    id: 3,
    name: 'Presentation_Q4.pptx',
    dateModified: 'Nov 7, 2024',
    size: 1520,
    type: 'pptx',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 4,
    name: 'Budget_2024.xlsx',
    dateModified: 'Nov 5, 2024',
    size: 380,
    type: 'xlsx',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 5,
    name: 'Project_Timeline.pdf',
    dateModified: 'Nov 3, 2024',
    size: 425,
    type: 'pdf',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 6,
    name: 'Meeting_Notes.txt',
    dateModified: 'Nov 1, 2024',
    size: 12,
    type: 'txt',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 7,
    name: 'Product_Image.png',
    dateModified: 'Oct 30, 2024',
    size: 2048,
    type: 'png',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 8,
    name: 'Client_Contract.pdf',
    dateModified: 'Oct 28, 2024',
    size: 890,
    type: 'pdf',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 9,
    name: 'Marketing_Strategy.docx',
    dateModified: 'Oct 25, 2024',
    size: 275,
    type: 'docx',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 10,
    name: 'Sales_Report.xlsx',
    dateModified: 'Oct 22, 2024',
    size: 445,
    type: 'xlsx',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 11,
    name: 'Team_Photo.jpg',
    dateModified: 'Oct 20, 2024',
    size: 1750,
    type: 'jpg',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 12,
    name: 'Project_Proposal.pdf',
    dateModified: 'Oct 18, 2024',
    size: 550,
    type: 'pdf',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 13,
    name: 'Code_Documentation.md',
    dateModified: 'Oct 15, 2024',
    size: 128,
    type: 'md',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 14,
    name: 'Customer_Survey.csv',
    dateModified: 'Oct 12, 2024',
    size: 892,
    type: 'csv',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 15,
    name: 'Website_Mockup.fig',
    dateModified: 'Oct 10, 2024',
    size: 3200,
    type: 'fig',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 16,
    name: 'Employee_Handbook.pdf',
    dateModified: 'Oct 8, 2024',
    size: 1280,
    type: 'pdf',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 17,
    name: 'Quarterly_Review.pptx',
    dateModified: 'Oct 5, 2024',
    size: 2100,
    type: 'pptx',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 18,
    name: 'Bug_Report.txt',
    dateModified: 'Oct 3, 2024',
    size: 45,
    type: 'txt',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 19,
    name: 'Logo_Final.ai',
    dateModified: 'Oct 1, 2024',
    size: 4500,
    type: 'ai',
    isFavorite: true,
    isSelected: false,
  },
  {
    id: 20,
    name: 'API_Documentation.md',
    dateModified: 'Sep 28, 2024',
    size: 320,
    type: 'md',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 21,
    name: 'Training_Video.mp4',
    dateModified: 'Sep 25, 2024',
    size: 25000,
    type: 'mp4',
    isFavorite: false,
    isSelected: false,
  },
  {
    id: 22,
    name: 'Financial_Report.xlsx',
    dateModified: 'Sep 22, 2024',
    size: 678,
    type: 'xlsx',
    isFavorite: true,
    isSelected: false,
  },
];
